version: "3.8"
services:
  mypostgres:
    container_name: "mypostgres"
    image: postgres:14.4
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: Pwd123#
  rabbit:
    container_name: "rabbit"
    image: rabbitmq:3.10.5-management
    ports:
      - "5672:5672"
      - "15672:15672"